export const REFRESH_USER_INFO = 'REFRESH_USER_INFO';
export const REFRESH_EXPIRE_INFO = 'REFRESH_EXPIRE_INFO';
export const REFRESH_PROMPT_MESSAGE = 'REFRESH_PROMPT_MESSAGE';
export const REFRESH_LOGIN_STATE = 'REFRESH_LOGIN_STATE';
export const REFRESH_INVALID_LOGIN_STATE = 'REFRESH_INVALID_LOGIN_STATE';
export const SAVE_LAST_VISIT = 'SAVE_LAST_VISIT';
export const REFRESH_APPLY_LIST = 'REFRESH_APPLY_LIST';

